server:
  port: 8080
  threads: 1
  development: false

app:
  clientPoolSize: 20
  clientTimeout: 10
  githubResourceV3: https://api.github.com
  githubUserAgent: exercise
  githubAccept: application/vnd.github.v3+json
  githubUserBasic: YWxsZWdyb0V4ZXJjaXNlOkNpSHVuQmFIaWR1andpNg==